<?php
/**
 * @file
 * Code for the Sierragraphs feature.
 */

include_once 'sierragraphs.features.inc';

/**
 * Implements hook_menu().
 */
function sierragraphs_menu() {
  $items['admin/config/system/sierragraphs'] = array(
    'title' => 'Sierragraphs',
    'description' => 'API credentials and other options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sierragraphs_auth_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'sierragraphs.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function sierragraphs_field_widget_form_alter(&$element, &$form_state, $context) {
  // Hide certain fields during node create
  if(!isset($form_state['node']->nid)) {
    if(isset($element['#field_name'])) {
      $sierragraphs_fields = array('title', 'author', 'summary', 'material_type', 'isbn', 'data');
      hide_sierragraphs_fields($element, $sierragraphs_fields);

      // Add validation to bib_id
      if($element['#field_name'] == 'field_sierragraphs_bib_id') {
        $element['#element_validate'][] = 'sierragraphs_bib_id_validate';
      }
    }
    // Jacket field is special case
    if(isset($element[0]) && $element[0]['#field_name'] == 'field_sierragraphs_jacket') {
      $element['#access'] = FALSE;
    }
  }
  else { // Hide certain fields during node edit
    if(isset($element['#field_name'])) {
      $sierragraphs_fields = array('bib_id', 'material_type', 'isbn', 'data');
      hide_sierragraphs_fields($element, $sierragraphs_fields);
    }
  }
}

/*
 * Iterates through an array of fields to hide them
 */
function hide_sierragraphs_fields(&$element, $sierragraphs_fields) {
  foreach ($sierragraphs_fields as $field) {
    if ($element['#field_name'] == 'field_sierragraphs_'.$field) {
      $element['#access'] = FALSE;
    }
  }
}

/*
 * Implements hook_validate().
 */
function sierragraphs_bib_id_validate($element, &$form_state, $complete_form) {
  $bib_id = preg_match('/[0-9]{7}/', $element['value']['#value'], $matches);
  if (!$bib_id) {
    form_error($element, t('The bib ID field must contain a 7 digit bib number.'));
  }
  else { // Strip value down to bib_id and populate rest of form
    form_set_value($element, array('value' => $matches[0]), $form_state);
    $sierra_data = sierragraphs_populate_with_data($matches[0]);
    if (!empty($sierra_data) && isset($sierra_data['data'])) {
      form_set_value(set_element_parents($element, 'field_sierragraphs_data'),
        array('value' => $sierra_data['data']), $form_state);
      form_set_value(set_element_parents($element, 'field_sierragraphs_title'),
        array('value' => $sierra_data['title']), $form_state);
      form_set_value(set_element_parents($element, 'field_sierragraphs_author'),
        array('value' => $sierra_data['author']), $form_state);
      form_set_value(set_element_parents($element, 'field_sierragraphs_material_type'),
        array('value' => $sierra_data['material_type']), $form_state);
      form_set_value(set_element_parents($element, 'field_sierragraphs_isbn'),
        array('value' => $sierra_data['isbn']), $form_state);
      form_set_value(set_element_parents($element, 'field_sierragraphs_summary'),
        array('value' => $sierra_data['summary']), $form_state);
    }
    else {
      form_error($element, t('The bib ID has no data.'));
    }
  }
}

/*
 * We use this to trick form_set_value into setting the field we want
 */
function set_element_parents($element, $name) {
  $element['#parents'][3] = $name;
  return $element;
}

/*
 * Takes the bib_id and returns an array with the fields we care about
 */
function sierragraphs_populate_with_data($bib_id) {
  $data = sierragraphs_get_bib_object($bib_id);
  $sierra_data = array();

  if (!empty($data) && isset($data->title) && isset($data->author) && isset($data->materialType->value)) {
    $sierra_data['data'] = json_encode($data);
    $sierra_data['title'] = $data->title;
    $sierra_data['author'] = sierragraphs_format_author($data->author);
    $sierra_data['material_type'] = $data->materialType->value;

    foreach ($data->varFields as $field) {
      if (isset($field->marcTag)) {
        if ($field->marcTag == '020') {
          foreach ($field->subfields as $sub) {
            if ($sub->tag == 'a') {
              $sierra_data['isbn'] = $sub->content;
            }
          }
        } elseif ($field->marcTag == '520') {
          foreach ($field->subfields as $sub) {
            if ($sub->tag == 'a') {
              $sierra_data['summary'] = $sub->content;
            }
          }
        }
      }
    }
  }

  return $sierra_data;
}

/*
 * Queries Sierra for bib object
 */
function sierragraphs_get_bib_object($bib_id) {
  module_load_include('inc', 'sierragraphs', 'sierragraphs.admin');
  // This URL queries Sierra with the default fields + all variable fields
  $host = variable_get('sierragraphs_auth_host', '');
  if (empty($host)) {
    return array();
  }
  $url = 'https://' . $host . '/iii/sierra-api/v1/bibs/' . $bib_id . '?fields=default,varFields';

  $token = sierragraphs_auth_token();
  $headers = array(
    'Authorization' => 'Bearer ' . $token,
  );
  $options = array('headers' => $headers);

  $response = drupal_http_request($url, $options);

  return json_decode($response->data);
}

/*
 * Does string reordering on the author returned from Sierra
 */
function sierragraphs_format_author($author = '') {
  if(strpos($author, ',') !== FALSE ) {
    $author_array = explode(',', $author);
    $author = '';
    foreach($author_array as $a) {
      $author = $a . ' ' . $author;
    }
  }
  return trim($author);
}